FROM python:3.9-slim

WORKDIR /app

RUN useradd -m appuser

RUN chown -R appuser:appuser /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

USER appuser

CMD ["python", "consumer.py"]
