frontend:
  name: frontend
  repository: osamaazm/shipr-frontend
  tag: latest
  replicas: 1
  containerPort: 80
  type: NodePort
  use_probes: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  service:
    port: 80
    targetport: 80
    nodePort: 30806
  labels:
    environment: production
    team: devops
    app: frontend
  resources:
    requests:
      set_requests: true
      memory: "128Mi"
      cpu: "500m"
    limits:
      set_limits: true
      memory: "256Mi"
      cpu: "1000m"
