apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{  .Values.redis.name }}-pvc
spec:
  storageClassName: {{ . .Values.redis.storageClassName }}
  accessModes:
    {{- range .Values.redis.volume.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{  .Values.redis.volume.storage }}
