apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetport }}
      {{- if or (eq .Values.payment.type "NodePort") (eq .Values.payment.type "LoadBalancer") }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  type: {{ .Values.frontend.type }}