apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels: 
    app: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        {{- if .Values.frontend.use_probes }}
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.path }}
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: {{ .Values.frontend.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.path }}
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: {{ .Values.frontend.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.periodSeconds }}
        startupProbe:
          httpGet:
            path: {{ .Values.frontend.path }}
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: {{ .Values.frontend.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.periodSeconds }}
        {{- end }}
        {{- if or .Values.frontend.resources.requests.set_requests .Values.frontend.resources.limits.set_limits }}
        resources:
        {{- end }}
          {{- if .Values.frontend.resources.requests.set_requests }}
          requests:
            memory: {{ .Values.frontend.resources.requests.memory }}
            cpu: {{ .Values.frontend.resources.requests.cpu }}
          {{- end }}
          {{- if .Values.frontend.resources.limits.set_limits }}
          limits:
            memory: {{ .Values.frontend.resources.limits.memory }}
            cpu: {{ .Values.frontend.resources.limits.cpu }}
          {{- end }}
