apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.inventory.name }}
  labels:
    {{- with .Values.inventory.labels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  replicas: {{ .Values.inventory.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.inventory.name }}
  template:
    metadata:
      labels:
        {{- with .Values.inventory.labels }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.inventory.name }}
        image: {{ .Values.inventory.repository }}:{{ .Values.inventory.tag }}
        ports:
        - containerPort: {{ .Values.inventory.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.inventory.configMapName }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.inventory.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.inventory.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.inventory.containerPort }}
          initialDelaySeconds: 15
          periodSeconds: 5
        resources: 
          requests:
            memory: {{ .Values.inventory.resources.requests.memory }}
            cpu: {{ .Values.inventory.resources.requests.cpu }}
          limits:
            memory: {{ .Values.inventory.resources.limits.memory }}
            cpu: {{ .Values.inventory.resources.limits.cpu }}
